# -*- coding: utf-8 -*-
"""task 2 .ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1g0obcohsgP_KTvReyEGunwl5QFshnSdj
"""

import random
import string

def generate_password(length):
    # Define the characters to choose from for the password
    characters = string.ascii_letters + string.digits + string.punctuation

    # Generate a password using random choices from the character set
    password = ''.join(random.choice(characters) for _ in range(length))

    return password

def main():
    print("Welcome to the Password Generator!")

    try:
        # Get user input for the desired password length
        password_length = int(input("Enter the desired password length: "))

        if password_length <= 0:
            print("Password length must be greater than 0.")
            return

        # Generate the password
        password = generate_password(password_length)

        # Display the generated password
        print("Generated Password:", password)
    except ValueError:
        print("Invalid input. Please enter a valid number.")

if __name__ == "__main__":
    main()